name: Rodar Teste de Performance
on: [push] # Sempre que voc锚 mudar o c贸digo, o rob么 come莽a!

jobs:
  run-artillery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar o Rob么
        run: npm install -g artillery
      - name: Executar o Ataque de Rob么s 
        run: artillery run --record --key ${{ secrets.ARTILLERY_API_KEY }} test.yml
